#!/usr/bin/env python3
import subprocess
import argparse
import re

AUTO_GEN_WARNING = (
    "This file is automatically generated by scripts/version.py. DO NOT EDIT.\n"
)

Version = tuple[int, int, int]

VERSION_PY = "bindings/python/version.py"
VERSION_HPP = "lib/include/triskel/utils/version.hpp"
VERSION_CMAKE = "cmake/version.cmake"


def run(*cmds: str) -> str:
    return (
        subprocess.check_output(list(cmds), stderr=subprocess.STDOUT).decode().strip()
    )


def get_git_version():
    try:
        tag = run("git", "describe", "--tags", "--abbrev=0")
        return tag.lstrip("v")
    except subprocess.CalledProcessError:
        return "0.0.0"


def git_tag_exists(tag: str) -> bool:
    try:
        run("git", "rev-parse", tag)
        return True
    except subprocess.CalledProcessError:
        return False


def create_git_tag(version: str) -> None:
    tag = f"v{version}"
    if git_tag_exists(tag):
        print(f"Git tag {tag} already exists. Skipping tag creation.")
    else:
        print(f"Committing changes")
        run("git", "add", VERSION_PY, VERSION_HPP, VERSION_CMAKE)
        run("git", "commit", "-m", f"Release version {version}")

        print(f"Creating Git tag: {tag}")
        run("git", "tag", "-a", tag, "-m", f"Version {version}")


def parse_version(version: str) -> Version:
    parts = version.split(".")
    if len(parts) != 3:
        raise ValueError(f"Invalid version format: {version}")
    return map(int, parts)


def bump_patch(version: Version) -> str:
    major, minor, patch = parse_version(version)
    return f"{major}.{minor}.{patch + 1}"


def bump_minor(version: Version) -> str:
    major, minor, _ = parse_version(version)
    return f"{major}.{minor + 1}.0"


def bump_major(version: Version) -> str:
    major, _, _ = parse_version(version)
    return f"{major + 1}.0.0"


def validate_version(version: str) -> None:
    if not re.match(r"^\d+\.\d+\.\d+$", version):
        raise ValueError(f"Invalid version format: {version}")


def write_version_py(version: str, path: str = VERSION_PY) -> None:
    with open(path, "w") as f:
        f.write(
            f"# {AUTO_GEN_WARNING}\n"  #
            f'__version__ = "{version}"\n'  #
            f""  #
        )


def write_version_hpp(version: str, path: str = VERSION_HPP) -> None:
    with open(path, "w") as f:
        f.write(
            f"#pragma once\n"  #
            f"//{AUTO_GEN_WARNING}\n"  #
            f'#define TRISKEL_VERSION "{version}"\n'  #
            f""  #
        )


def write_version_cmake(version: str, path: str = VERSION_CMAKE) -> None:
    with open(path, "w") as f:
        f.write(
            f"# {AUTO_GEN_WARNING}\n"  #
            f'set(TRISKEL_VERSION "{version}")\n'  #
            f""  #
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate version files from Git tags or manual version"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--set-version", help="Specify the version manually (e.g., 1.2.3)"
    )
    group.add_argument(
        "--bump-patch",
        action="store_true",
        help="Bump path version from the latest Git tag",
    )
    group.add_argument(
        "--bump-minor",
        action="store_true",
        help="Bump minor version from the latest Git tag",
    )
    group.add_argument(
        "--bump-major",
        action="store_true",
        help="Bump major version from the latest Git tag",
    )

    args = parser.parse_args()

    is_new_tag = False

    if args.set_version:
        version = args.set_version
        validate_version(version)
        is_new_tag = True
    else:
        version = get_git_version()
        if args.bump_patch:
            version = bump_patch(version)
            is_new_tag = True
        elif args.bump_minor:
            version = bump_minor(version)
            is_new_tag = True
        elif args.bump_major:
            version = bump_major(version)
            is_new_tag = True

    print(f"Using version: {version}")

    write_version_py(version)
    write_version_hpp(version)
    write_version_cmake(version)

    if is_new_tag:
        create_git_tag(version)
